version: '3.7'

services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/DjangoExampleProject/
    ports:
      - 8000:8000
    depends_on:
      - pgdb
  pgdb:
    container_name: pgdb
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db

volumes:
  postgres_data:
